services:
  backend: # name of the service is the DNS name as mentioned in nginx.config
    image: my-backend-app
    build:
      context: .
      dockerfile: app.Dockerfile
    networks:
      - app-network
  nginx-proxy:
    image: proxy_nginx
    build:
      context: ./docker #This is the path for the docker file
      dockerfile: nginx.dockerfile # docker file name
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
